### ISSUE TITLE
0 and 1 argument results not working for +

### ISSUE THREAD

**Issue by jhelmsen** [tel/clatrix#61]
The clojure.core + operation generates a 0 for 0 arguments being passed to it, and operates as the identity for 1 argument being passed to it.  This makes operations on lists, such as '(apply + (...)) work much more cleanly.  It would be good if the matrix + operator acted more like the standard clojure.core + operator, since we would not need to check the number of arguments explicitly before applying it.

**Comment by mikera** [comment]
Good idea, I've added in my latest development branch, should merge in soon.
