### ISSUE TITLE
thought about switching to neanderthal

### ISSUE THREAD

**Issue by carocad** [tel/clatrix#68]
Hey Joseph,
To be honest I have not (yet) used clatrix but I am fully aware of its potential.

This is not an issue per se, but rather just to let you know something.
There has been some rather interesting developing going on regarding Clojure numeric computations. I want to raise your attention to two open source libraries: [ClojureCL](https://github.com/uncomplicate/clojurecl) and [neanderthal](https://github.com/uncomplicate/neanderthal). They are based on ATLAS implementation as well but seem to be very optimized.

According to neanderthal's website, its matrix computation can be as much as 5x faster than JBlas, and from his statements, it seems that with the support of GPUs (next release), it can be even faster (see [comment](https://clojurians.slack.com/archives/uncomplicate/p1462885850000045))

Hope it helps,

PS: I am in no way affiliated to them. I just wanted to share the knowledge ;)

**Comment by mikera** [comment]
I think that Clatrix is pretty much tied to JBlas (it is a wrapper library after all)

A better approach IMHO would be implementing the core.matrix protocols for neanderthal directly. This would make neanderthal compatible with Clatrix / other core.matrix implementations. This is something that the author has said would be happy to see done, but doesn't personally have time to do - might be an interesting mini-project.
