### ISSUE TITLE
warning related to `abs` function when using Clojure 1.11

### ISSUE THREAD

**Issue by jumarko** [tel/clatrix#72]
```
WARNING: abs already refers to: #'clojure.core/abs in namespace: clatrix.core, being replaced by: #'clatrix.core/abs
```
`clojure.core/abs` should be excluded, similar to here: https://github.com/clojure/tools.analyzer/commit/599274104faad08f31607063ac8d7540f9e30af6

**Comment by jumarko** [comment]
@tel or @mikera anything you can do about the warning above?

**Comment by tel** [comment]
It's been a long while since I've maintained this package, unfortunately. If Mike has thoughts then he should chime in. Otherwise, if you're an active user then I'd be inclined to give you a commit bit.

**Comment by jumarko** [comment]
I realized we were using this in a project that doesn't need the dependency anymore :).
Closing.
